### ISSUE TITLE
Official release with `list lists` command

### ISSUE THREAD

**Issue by mwarkentin** [hubot-scripts/hubot-trello#3]
Any chance of getting a release pushed to npm with the `list lists` command? Seems like it would be quite helpful. :)

**Comment by syntax922** [comment]
I think this is already there, as it was there when I downloaded from npm a couple nights ago. Can double check? (I'm unfamiliar with npm updates)

**Comment by mwarkentin** [comment]
If so, it might've happened via uploading a new version of 0.1.1 to npm - since the `list lists` PR came after 0.1.1 was set:

![](https://mwarkentin-snaps.s3.amazonaws.com/Commits__hubot-scriptshubot-trello_2016-03-08_13-03-12.png)

**Comment by dylanh724** [comment]
list lists is not working in npm as of now

**Comment by pierreozoux** [comment]
Please :)

**Comment by syntax922** [comment]
This is in the trunk, again I believe this is on NPM too.

**Comment by pierreozoux** [comment]
double checked now:

```
cd /tmp 
mkdir test
cd test
npm install hubot-trello
cd node_modules/hubot-trello
cat src/trello.coffee | grep "create list"
```

this is not on npm :)

**Comment by syntax922** [comment]
@codeimpossible Any idea when NPM will be updated?

@pierreozoux in the meantime you can download the file from github and you'll have it.

**Comment by pierreozoux** [comment]
> @pierreozoux https://github.com/pierreozoux in the meantime you can
> download the file from github and you'll have it.
> It is what I did, but the hubot I'm using (for rocketchat) was a lot
> easier if used with an npm package :) (than manually)

Cheers!

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hubot-scripts/hubot-trello/issues/3#issuecomment-216986531

## 

I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by codeimpossible** [comment]
Sorry everyone i've had this on my to do list for a while and I've completely dropped the ball there. I'll push the new version to NPM tonight when I get home.

**Comment by codeimpossible** [comment]
v0.2.0 has been published. Let me know if there are any issues!
