### ISSUE TITLE
No response from bot

### ISSUE THREAD

**Issue by jwkicklighter** [hubot-scripts/hubot-trello#5]
I'm not getting any responses from the bot with trello commands, but it seems to be installed properly. When I say "hubot help" I see a few trello commands in the list. Not seeing any errors thrown in the heroku logs, and I have my env variables showing up.

**Comment by misterdai** [comment]
I'm getting the same thing.  Set up the API ID and Token variables, plus the board ID.  Hubot is seeing the module as the help commands have appeared, but it doesn't give any response to the commands.  No actions taking place on the relevant board, responses from the bot or errors at the console.

**Comment by misterdai** [comment]
Worked it out, I was using hubot with the Slack adapter and typing commands from the desktop client (OS X version).  This was turning my normal quote characters `"` and `'` into their curled versions `‘  “  ’  ”`.  So after ages of banging my head against a brick wall it wasn't really the fault of this module.  Although, I may throw a pull request over just to allow for more quote characters so others do have to suffer as I did ;)

**Comment by jwkicklighter** [comment]
Thank you for figuring this out! A PR would be really appreciated if you
have the time. We can't be the only ones with this issue :)

Jordan Kicklighter

**Comment by misterdai** [comment]
@jwkicklighter could swear I had done this last week but must be going mad ;)  Have made sure the pull request for the change is there now.

Just need @codeimpossible or whoever else has access to give it the once over :)

**Comment by codeimpossible** [comment]
Thanks for all the work on this, it's really appreciated

**Comment by codeimpossible** [comment]
going to close this since we've merged the issues related to it.
